version: '2'

services:
  # order-api:
  #   build: .
  #   hostname: buisness-api
  #   container_name: business_api
  #   ports:
  #     - 5001:5001
  #     - 5000:5000
  mongodb:
    image: mongo:latest
    hostname: kafka-mongo
    container_name: kafkatests-mongodb
    environment: 
      MONGODB_USER: mongodb
      MONGODB_PASS: mongodb
    volumes: 
      - 'kafkatests-mongodb-data:/data/db'
    ports: 
      - '27017:27017'
    command: mongod
  zookeeper-kafkatests:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper_kafkatests
    hostname: zookeeper-kafkatests
    ports:
      - '2181:2181'
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka-tests:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka
    container_name: kafka_tests
    depends_on: 
      - zookeeper-kafkatests
    ports: 
      - '9092:9092'
    environment: 
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-kafkatests:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
volumes:
  kafkatests-mongodb-data: {}